### ISSUE TITLE
Leaderboard is not sorted correctly

### ISSUE THREAD

**Issue by ghost** [Slush0Puppy/speedrunbot#10]
...

**Comment by AnInternetTroll** [comment]
Super late to this, but here's my take I guess.
Using BeautifulSoup with HTML and stuff like that is in general bad practice. The response is a lot bigger which means slower response times for the bot. Given the new updates ELO has been pumping out with the frontend aspect it's also very unstable. 
If I were to guess it seems like the API only updates once every 5-10 minutes. If the run still shows up as 5th place then it's kind of out of the bot's control. Also I'm not sure how happy speedrun.com would be if a discord bot started web scrapping the website, especially given the traffic problems and server issues they have been having lately. The API routes are a lot less demanding and stressing so we are doing them a favor with those.
